# These are supported funding model platforms

github: [singhaditya28]
patreon: singhaditya28
open_collective: # Replace with a single Open Collective username
ko_fi: singhaditya28
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL